name: Build
on: [push, pull_request]

jobs:
  run-test-php7.3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "7.3"

      - name: PHPUnit Tests PHP 7.3
        uses: php-actions/phpunit@master
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml.dist
          args: --coverage-text
          php_extensions: xdebug
          php_version: 7.3
          version: 9
        env:
          XDEBUG_MODE: coverage

  run-test-php8.1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"

      - name: PHPUnit Tests PHP 78.1
        uses: php-actions/phpunit@master
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml.dist
          args: --coverage-text
          php_extensions: xdebug
          php_version: 8.1
          version: 9
        env:
          XDEBUG_MODE: coverage